plugin.plugin_configuration.search_api_datasource.solr_document:
  type: mapping
  label: "Solr document datasource configuration"
  mapping:
    id_field:
      type: string
      label: "ID field"
    advanced:
      type: mapping
      label: "Advanced configuration"
      mapping:
        request_handler:
          type: string
          label: "Request handler"
