favicon:
  mimetype: image/png
  path: 'public://screenshot.png'
  url: 'https://seattlecentral.dev.dd:8443/themes/custom/scc_heros/favicon.ico'
  use_default: 0
schemas:
  bootstrap: 8000
  scc_heros: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://seattle-central-college-central-to-the-community-for-50-years_0_0.png'
  url: ''
  use_default: 0
table_responsive: '-1'
table: ''
